### ISSUE TITLE
Problems of running collect_expert_demon_data.py

### ISSUE THREAD

**Issue by Yingxiu-Chang** [ai4ce/DeepExplorer#1]
Hi, 
I followed your [tutorial](https://docs.google.com/document/d/1XujCOLZ3d-76s0n1U7U1S_X2c2eHNGTT4ZTIgBPw8NI/edit?usp=sharing) on installing habitat for our lab's junior member. 
When I try to run your collect_expert_demon_data.py, it shows following:
```
Traceback (most recent call last):
  File "collect_expert_demon_data.py", line 12, in <module>
    from habitat_baselines.utils.common import batch_obs
  File "/home/hugh/Data_Collection/habitat-lab/habitat_baselines/__init__.py", line 7, in <module>
    from habitat_baselines.common.base_il_trainer import BaseILTrainer
  File "/home/hugh/Data_Collection/habitat-lab/habitat_baselines/common/base_il_trainer.py", line 10, in <module>
    from habitat_baselines.common.base_trainer import BaseTrainer
  File "/home/hugh/Data_Collection/habitat-lab/habitat_baselines/common/base_trainer.py", line 14, in <module>
    from habitat_baselines.common.tensorboard_utils import TensorboardWriter
  File "/home/hugh/Data_Collection/habitat-lab/habitat_baselines/common/tensorboard_utils.py", line 11, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/hugh/anaconda3/envs/habitat/lib/python3.6/site-packages/torch-1.10.2-py3.6-linux-x86_64.egg/torch/utils/tensorboard/__init__.py", line 13, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/home/hugh/anaconda3/envs/habitat/lib/python3.6/site-packages/torch-1.10.2-py3.6-linux-x86_64.egg/torch/utils/tensorboard/writer.py", line 13, in <module>
    from tensorboard.summary.writer.event_file_writer import EventFileWriter
  File "/home/hugh/anaconda3/envs/habitat/lib/python3.6/site-packages/tb_nightly-2.17.0a20240303-py3.6.egg/tensorboard/summary/__init__.py", line 22, in <module>
    from tensorboard.summary import v1  # noqa: F401
  File "/home/hugh/anaconda3/envs/habitat/lib/python3.6/site-packages/tb_nightly-2.17.0a20240303-py3.6.egg/tensorboard/summary/v1.py", line 23, in <module>
    from tensorboard.plugins.histogram import summary as _histogram_summary
  File "/home/hugh/anaconda3/envs/habitat/lib/python3.6/site-packages/tb_nightly-2.17.0a20240303-py3.6.egg/tensorboard/plugins/histogram/summary.py", line 35, in <module>
    from tensorboard.plugins.histogram import summary_v2
  File "/home/hugh/anaconda3/envs/habitat/lib/python3.6/site-packages/tb_nightly-2.17.0a20240303-py3.6.egg/tensorboard/plugins/histogram/summary_v2.py", line 35, in <module>
    from tensorboard.util import tensor_util
  File "/home/hugh/anaconda3/envs/habitat/lib/python3.6/site-packages/tb_nightly-2.17.0a20240303-py3.6.egg/tensorboard/util/tensor_util.py", line 20, in <module>
    from tensorboard.compat.tensorflow_stub import dtypes, compat, tensor_shape
  File "/home/hugh/anaconda3/envs/habitat/lib/python3.6/site-packages/tb_nightly-2.17.0a20240303-py3.6.egg/tensorboard/compat/tensorflow_stub/__init__.py", line 25, in <module>
    from . import app  # noqa
  File "/home/hugh/anaconda3/envs/habitat/lib/python3.6/site-packages/tb_nightly-2.17.0a20240303-py3.6.egg/tensorboard/compat/tensorflow_stub/app.py", line 21, in <module>
    from . import flags
  File "/home/hugh/anaconda3/envs/habitat/lib/python3.6/site-packages/tb_nightly-2.17.0a20240303-py3.6.egg/tensorboard/compat/tensorflow_stub/flags.py", line 25, in <module>
    from absl.flags import *  # pylint: disable=wildcard-import
  File "/home/hugh/anaconda3/envs/habitat/lib/python3.6/site-packages/absl_py-2.1.0-py3.6.egg/absl/flags/__init__.py", line 35, in <module>
    from absl.flags import _argument_parser
  File "/home/hugh/anaconda3/envs/habitat/lib/python3.6/site-packages/absl_py-2.1.0-py3.6.egg/absl/flags/_argument_parser.py", line 82, in <module>
    class ArgumentParser(Generic[_T], metaclass=_ArgumentParserCache):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

```
I not sure did I install correctly or what specific problem that I encounterd?
Best regards
Hugh

**Comment by IrvingF7** [comment]
Hi! Thanks for your question.
@yuhanghe01 was responsible for the expert data generation script. Maybe he can help you with that!

Cheers

**Comment by Yingxiu-Chang** [comment]
Thank you so much for your help. I changed the tensorflow version according to the requirements and solved this problem. 
Best
Hugh

**Comment by yuhanghe01** [comment]
Hi @Yingxiu-Chang , thanks for your interest in our work. I am glad to hear that you solved this problem already.
